# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/centos-7.4"
  config.vm.box_version = "201803.24.0"
  config.vm.box_check_update = false
  config.vm.boot_timeout = 0

  config.vm.box_url = "https://app.vagrantup.com/bento/boxes/centos-7.4"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false

 
  config.vm.define "docker_hub", primary: true, autostart:true do |docker_hub|
    docker_hub.vm.provider :virtualbox do |vb|
      vb.name = "docker_hub"
      vb.gui = false
      vb.customize ["modifyvm", :id, "--ioapic", "on"  ]
      vb.customize ["modifyvm", :id, "--cpus"  , "2"   ]
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    docker_hub.vm.hostname = "docker-hub"
    docker_hub.vm.network "private_network", ip: "192.168.33.15"
    
    docker_hub.vm.synced_folder "~/vagrant_shared", "/vagrant_shared", create: true

    docker_hub.vm.provision "shell", path: "../scripts/add_swap_file.sh"
    docker_hub.vm.provision "shell", inline: "sudo yum -y install java java-devel"
    docker_hub.vm.provision "shell", inline: $install_mvn
    docker_hub.vm.provision "shell", inline: $install_docker_ce

  end
end

### Install Maven Script
########################
$install_mvn = <<-SCRIPT
sudo rm -rf /usr/local/apache-maven* /tmp/apache-maven*
wget -q http://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz -P /tmp/
sudo tar -xzf /tmp/apache-maven-3.5.3-bin.tar.gz -C /usr/local/
sudo ln -sf /usr/local/apache-maven-3.5.3/bin/mvn /usr/bin/mvn
SCRIPT
########################

### Install Docker-CE Script
########################
$install_docker_ce = <<-SCRIPT
# Installing docker
sudo sed -i 's/permissive/disabled/g' /etc/selinux/config
sudo yum -y install yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum -y install docker-ce
sudo service docker start

sudo chkconfig docker on
sudo chmod 777 /var/run/docker.sock
SCRIPT
########################

